# main.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ide-flow/locations/us-central1/spaces/default-space/applicationTemplates/real-estate-agent-re2024

module "backend-re2024" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.26.0"
  project_id                    = "ide-flow"
  location                      = "us-central1"
  service_name                  = "backend-re2024"
  containers                    = [{"env_vars" = {"GEMINI_API_KEY" = "TODO_REPLACE_WITH_ACTUAL_KEY"}, "ports" = {"container_port" = 8000}, "container_image" = "us-central1-docker.pkg.dev/ide-flow/real-estate-repo/backend:latest"}]
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "frontend-re2024" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.26.0"
  project_id                    = "ide-flow"
  location                      = "us-central1"
  service_name                  = "frontend-re2024"
  containers                    = [{"container_image" = "us-central1-docker.pkg.dev/ide-flow/real-estate-repo/frontend:latest", "env_vars" = {"VITE_API_URL" = module.backend-re2024.service_uri}, "ports" = {"container_port" = 8080}}]
  gpu_zonal_redundancy_disabled = false
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "lb-frontend-re2024" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "lb-frontend-re2024"
  project_id    = "ide-flow"
  url_map_input = concat(module.lb-backend-api-re2024.backend_service_info, module.lb-backend-web-re2024.backend_service_info)
}
module "lb-backend-api-re2024" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v14.2.0"
  name       = "lb-backend-api-re2024"
  project_id = "ide-flow"
  serverless_neg_backends = [{
    region          = module.backend-re2024.location
    service_name    = module.backend-re2024.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  host_path_mappings = [{"host" = "*", "path" = "/api/*"}]
}
module "lb-backend-web-re2024" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v14.2.0"
  name       = "lb-backend-web-re2024"
  project_id = "ide-flow"
  serverless_neg_backends = [{
    region          = module.frontend-re2024.location
    service_name    = module.frontend-re2024.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  host_path_mappings = [{"host" = "*", "path" = "/*"}]
}
