# outputs.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ide-flow/locations/us-central1/spaces/default-space/applicationTemplates/real-estate-agent-re2024

output "backend-re2024_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.backend-re2024.service_uri
}
output "frontend-re2024_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-re2024.service_uri
}
output "lb-frontend-re2024_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.lb-frontend-re2024.external_ip
}
output "lb-frontend-re2024_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.lb-frontend-re2024.external_ipv6_address
}
output "lb-frontend-re2024_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.lb-frontend-re2024.ip_address_internal_managed_http
}
output "lb-frontend-re2024_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.lb-frontend-re2024.ip_address_internal_managed_https
}
