# providers.tf

# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/ide-flow/locations/us-central1/spaces/default-space/applicationTemplates/real-estate-agent-re2024

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
}
